from __future__ import annotations

import json
from statistics import mean
from typing import Any
from xml.sax.saxutils import escape

from process_reimagination_agent.config import Settings
from process_reimagination_agent.ingestion import ingest_manifest
from process_reimagination_agent.models import FrictionItem, InputManifest, PathDecision
from process_reimagination_agent.regional_rules import apply_regional_overrides_to_decision, detect_regional_nuances
from process_reimagination_agent.validators import count_words, validate_mermaid_xml, validate_strategy_report


def _fallback_friction_from_pain_points(pain_points: list[str], combined_text: str) -> list[FrictionItem]:
    frictions: list[FrictionItem] = []
    for pain_point in pain_points:
        text = pain_point.lower()
        if any(token in text for token in ["email", "pdf", "spreadsheet", "manual entry", "transcribing"]):
            frictions.append(
                FrictionItem(
                    current_manual_action=pain_point,
                    friction_type="Human transcription and unstructured intake triage",
                    proposed_path="C",
                    rationale="Requires perception over unstructured documents and adaptive extraction checks.",
                    expected_kpi_shift="60-80% faster intake with lower transcription defects",
                    requires_perception=True,
                    requires_reasoning=True,
                    requires_adaptive_action=False,
                    source_evidence="Pain point inventory",
                )
            )
            continue

        if any(token in text for token in ["dispute", "deduction", "trade promo", "shortage"]):
            frictions.append(
                FrictionItem(
                    current_manual_action=pain_point,
                    friction_type="Manual dispute triage and evidence reconciliation",
                    proposed_path="C",
                    rationale="Requires reasoning across invoices, POD, and policy context.",
                    expected_kpi_shift="30-50% dispute cycle-time reduction and DSO improvement",
                    requires_perception=True,
                    requires_reasoning=True,
                    requires_adaptive_action=True,
                    source_evidence="Pain point inventory",
                )
            )
            continue

        if any(token in text for token in ["custom", "z-", "deviation", "non-standard", "tcode"]):
            frictions.append(
                FrictionItem(
                    current_manual_action=pain_point,
                    friction_type="ERP deviation from standard process template",
                    proposed_path="A",
                    rationale="Candidate for core standardization to reduce technical debt.",
                    expected_kpi_shift="Lower support overhead and faster release velocity",
                    requires_perception=False,
                    requires_reasoning=False,
                    requires_adaptive_action=False,
                    source_evidence="Pain point inventory",
                )
            )
            continue

        frictions.append(
            FrictionItem(
                current_manual_action=pain_point,
                friction_type="Deterministic coordination and status handling",
                proposed_path="B",
                rationale="Best handled via workflow orchestration and rule-driven automation.",
                expected_kpi_shift="20-40% cycle-time improvement in repetitive tasks",
                requires_perception=False,
                requires_reasoning=False,
                requires_adaptive_action=False,
                source_evidence="Pain point inventory",
            )
        )

    if frictions:
        return frictions

    # PHASE 1 must run even with sparse evidence.
    return [
        FrictionItem(
            current_manual_action="Human receives mixed-format order requests and re-keys them into ERP.",
            friction_type="Cognitive middleware bridging across channels and core system",
            proposed_path="C",
            rationale="Requires unstructured perception and adaptive handling for partial information.",
            expected_kpi_shift="Significant reduction in manual effort and keying errors",
            requires_perception=True,
            requires_reasoning=True,
            requires_adaptive_action=True,
            source_evidence="Sparse-input fallback generated by mandatory Phase 1",
        )
    ]


def _friction_items_from_state(state: dict[str, Any]) -> list[FrictionItem]:
    logs = state.get("cognitive_friction_logs", [])
    items: list[FrictionItem] = []
    for log in logs:
        try:
            items.append(FrictionItem.model_validate(log))
        except Exception:
            continue
    if items:
        return items
    return _fallback_friction_from_pain_points(state.get("pain_points", []), "")


def _classify_path(item: FrictionItem) -> str:
    # Clean Core policy: prefer standardization (A) where business behavior is not unique.
    if "standard" in item.friction_type.lower() or "deviation" in item.friction_type.lower():
        return "A"
    # Side-Car policy: use deterministic automation (B) for repetitive rule-based tasks.
    if not (item.requires_perception or item.requires_reasoning or item.requires_adaptive_action):
        return "B"
    # Agentic path (C) reserved for perception/reasoning/adaptive action.
    return "C"


def _decision_confidence(item: FrictionItem, iteration_count: int, evidence_penalty: bool) -> float:
    base = 0.90
    if item.requires_perception or item.requires_reasoning or item.requires_adaptive_action:
        base += 0.02
    if item.source_evidence:
        base += 0.03
    base += min(iteration_count, 2) * 0.02
    if evidence_penalty:
        base -= 0.05
    return max(0.50, min(0.99, base))


def Synthesizer_Node(state: dict[str, Any], settings: Settings) -> dict[str, Any]:
    raw_inputs = dict(state.get("raw_inputs", {}))
    manifest_data = raw_inputs.get("manifest", {})

    manifest = InputManifest.model_validate(
        {
            "process_name": state.get("process_name") or manifest_data.get("process_name", "Order Intake"),
            "context_region": state.get("context_region") or manifest_data.get("context_region", "Global"),
            "pain_points": state.get("pain_points") or manifest_data.get("pain_points", []),
            "files": manifest_data.get("files", []),
            "additional_context": manifest_data.get("additional_context", {}),
        }
    )

    ingest_result = ingest_manifest(manifest)
    combined_text = ingest_result.get("combined_text", "")
    raw_inputs.update(ingest_result)

    regional_nuances = detect_regional_nuances(combined_text=combined_text, context_region=manifest.context_region)
    frictions = _fallback_friction_from_pain_points(manifest.pain_points, combined_text)

    phase_status = dict(state.get("phase_status", {}))
    phase_status["phase_1_current_reality_synthesis"] = "completed"

    errors = list(state.get("errors", []))
    extraction_errors = ingest_result.get("extraction_errors", [])
    if extraction_errors:
        errors.extend(extraction_errors)

    return {
        "raw_inputs": raw_inputs,
        "process_name": manifest.process_name,
        "context_region": manifest.context_region,
        "pain_points": manifest.pain_points,
        "cognitive_friction_logs": [item.model_dump() for item in frictions],
        "regional_nuances": regional_nuances,
        "phase_status": phase_status,
        "errors": errors,
    }


def Input_Refiner_Node(state: dict[str, Any], settings: Settings) -> dict[str, Any]:
    iteration = int(state.get("refinement_iterations", 0)) + 1
    feedback = list(state.get("quality_feedback", []))
    feedback.append(
        (
            f"Refinement pass {iteration}: strengthened evidence mapping and clarified "
            "Path A/B/C rationale to close Trust Gap."
        )
    )

    refined_logs = []
    for item in _friction_items_from_state(state):
        payload = item.model_dump()
        if not payload.get("source_evidence"):
            payload["source_evidence"] = "Refined using quality feedback and source documents"
        payload["rationale"] = (
            f"{payload['rationale']} Refinement pass {iteration} validated against Clean Core and Side-Car policies."
        )
        refined_logs.append(payload)

    phase_status = dict(state.get("phase_status", {}))
    phase_status["phase_1_current_reality_synthesis"] = "completed"

    return {
        "refinement_iterations": iteration,
        "quality_feedback": feedback,
        "cognitive_friction_logs": refined_logs,
        "phase_status": phase_status,
    }


def Architect_Node(state: dict[str, Any], settings: Settings) -> dict[str, Any]:
    friction_items = _friction_items_from_state(state)
    path_decisions: list[dict[str, Any]] = []
    iteration = int(state.get("refinement_iterations", 0))
    region = state.get("context_region", "Global")

    evidence_penalty = bool(state.get("errors"))
    for item in friction_items:
        path = _classify_path(item)
        # Guardrail: Path C is allowed only when perception/reasoning/adaptive action is needed.
        if path == "C" and not (item.requires_perception or item.requires_reasoning or item.requires_adaptive_action):
            path = "B"

        decision = PathDecision(
            current_manual_action=item.current_manual_action,
            path=path,  # type: ignore[arg-type]
            confidence=_decision_confidence(item, iteration_count=iteration, evidence_penalty=evidence_penalty),
            rationale=f"{item.rationale} Classified via mandatory Phase 2 suitability assessment.",
            clean_core_guardrail=(
                "Keep ERP kernel standard; route custom logic to Side-Car orchestration and APIs only."
            ),
            side_car_component=(
                "Agentic Intake Orchestrator" if path == "C" else "Workflow Automation Side-Car"
            ),
            regional_overrides=[],
        ).model_dump()

        decision = apply_regional_overrides_to_decision(
            decision,
            region=region,
            order_status=state.get("raw_inputs", {}).get("order_status", "open"),
            confidence_score=decision["confidence"],
            channel=state.get("raw_inputs", {}).get("channel", ""),
        )
        path_decisions.append(decision)

    overall_confidence = mean([d["confidence"] for d in path_decisions]) if path_decisions else 0.0
    if "force_confidence_override" in state:
        overall_confidence = float(state["force_confidence_override"])

    quality_feedback = list(state.get("quality_feedback", []))
    if overall_confidence <= settings.confidence_threshold:
        quality_feedback.append(
            (
                f"Confidence {overall_confidence:.2%} below threshold "
                f"{settings.confidence_threshold:.2%}. Additional refinement required."
            )
        )

    phase_status = dict(state.get("phase_status", {}))
    phase_status["phase_2_agentic_reasoning"] = "completed"

    return {
        "path_decisions": path_decisions,
        "confidence_score": round(overall_confidence, 4),
        "quality_feedback": quality_feedback,
        "phase_status": phase_status,
    }


def Quality_Control_Node(state: dict[str, Any], settings: Settings) -> dict[str, Any]:
    confidence = float(state.get("confidence_score", 0.0))
    refinement_iterations = int(state.get("refinement_iterations", 0))
    errors = list(state.get("errors", []))
    feedback = list(state.get("quality_feedback", []))
    phase_status = dict(state.get("phase_status", {}))

    if confidence > settings.confidence_threshold:
        phase_status["quality_control"] = "pass"
        return {"quality_gate_result": "blueprint", "phase_status": phase_status}

    if refinement_iterations >= settings.max_refinement_loops:
        phase_status["quality_control"] = "escalated"
        errors.append(
            (
                f"Trust Gap threshold not met after {refinement_iterations} refinements. "
                "Escalate to human review for source quality and policy verification."
            )
        )
        return {"quality_gate_result": "escalate", "phase_status": phase_status, "errors": errors}

    phase_status["quality_control"] = "refine"
    feedback.append(
        (
            "Quality Control loop triggered: confidence below 95%, returning to Input Refiner "
            "before blueprint generation."
        )
    )
    return {"quality_gate_result": "refine", "phase_status": phase_status, "quality_feedback": feedback}


def quality_route(state: dict[str, Any]) -> str:
    return str(state.get("quality_gate_result", "refine"))


def Human_Escalation_Node(state: dict[str, Any], settings: Settings) -> dict[str, Any]:
    phase_status = dict(state.get("phase_status", {}))
    phase_status["phase_3_blueprint_generation"] = "blocked_pending_human_escalation"
    errors = list(state.get("errors", []))
    if not errors:
        errors.append("Human escalation required before blueprint generation.")
    return {"phase_status": phase_status, "errors": errors}


def _build_cognitive_friction_table(cognitive_friction_logs: list[dict[str, Any]]) -> str:
    header = (
        "| [Current Manual Action] | Friction Type | Proposed Path | Rationale | Expected KPI Shift |\n"
        "|---|---|---|---|---|"
    )
    rows = []
    for item in cognitive_friction_logs:
        rows.append(
            "| {action} | {ftype} | {path} | {rationale} | {kpi} |".format(
                action=item.get("current_manual_action", "N/A"),
                ftype=item.get("friction_type", "N/A"),
                path=item.get("proposed_path", "N/A"),
                rationale=item.get("rationale", "N/A"),
                kpi=item.get("expected_kpi_shift", "N/A"),
            )
        )
    return "\n".join([header, *rows]) if rows else header


def _add_unique_section(
    section_order: list[str],
    section_registry: dict[str, str],
    heading: str,
    body: str,
) -> None:
    if heading in section_registry:
        raise ValueError(f"Duplicate protected section detected during generation: {heading}")
    section_order.append(heading)
    section_registry[heading] = body.strip()


def _render_report_from_sections(
    report_title: str,
    section_order: list[str],
    section_registry: dict[str, str],
) -> str:
    parts = [report_title]
    for heading in section_order:
        parts.append(f"{heading}\n{section_registry[heading]}")
    return "\n\n".join(parts)


def _build_strategy_report(state: dict[str, Any], settings: Settings) -> str:
    process_name = state.get("process_name", "Process")
    context_region = state.get("context_region", "Global")
    trust_gap_phase = state.get("trust_gap_phase", "Shadow")
    cognitive_friction_logs = state.get("cognitive_friction_logs", [])
    path_decisions = state.get("path_decisions", [])

    table = _build_cognitive_friction_table(cognitive_friction_logs)
    decision_lines = [
        f"- **{d.get('path')}** for `{d.get('current_manual_action')}`: {d.get('rationale')} "
        f"(confidence {d.get('confidence', 0):.0%})"
        for d in path_decisions
    ]
    regional_nuances = json.dumps(state.get("regional_nuances", {}), indent=2)

    report_title = f"# Re-Imagined Strategy Report: {process_name}"
    section_order: list[str] = []
    section_registry: dict[str, str] = {}

    _add_unique_section(
        section_order,
        section_registry,
        "## Executive Summary",
        (
            f"The One Big Move for {process_name} in {context_region} is to replace human middleware with a "
            "Side-Car intelligence and orchestration layer that protects the SAP core while accelerating order-cycle "
            "execution. This architecture treats every intake channel as an event source, every exception as a managed "
            "decision point, and every ERP transaction as a standards-based API call rather than a custom-coded branch. "
            "The strategic benefit is immediate: higher touchless throughput, lower transcription defects, faster "
            "exception closure, and lower operational risk across regional variations. The design also keeps long-term "
            "cost under control by avoiding core-kernel customization and by consolidating complex logic into reusable "
            "side-car services. The methodology is intentionally strict: Phase 1 captures current reality and cognitive "
            "friction, Phase 2 maps each friction to Path A/B/C with explicit suitability logic, and Phase 3 produces a "
            "deployable blueprint backed by trust controls. The operating model is therefore transformation-ready and "
            "audit-ready from day one."
        ),
    )

    _add_unique_section(
        section_order,
        section_registry,
        "## Cognitive Friction Analysis",
        (
            "The following table is the mandatory friction inventory used by the Architect phase. Each row identifies "
            "where humans currently act as middleware, what category of friction exists, and which intervention path "
            "provides the safest and fastest improvement without violating Clean Core policies.\n\n"
            f"{table}"
        ),
    )

    _add_unique_section(
        section_order,
        section_registry,
        "## Architecture of the Future State",
        (
            "The future state is a hub-and-spoke operating model where the Agentic Side-Car is the controlled brain "
            "between channels and SAP. Personas are explicit: **The Intake Scribe** extracts and normalizes incoming "
            "order payloads; **The Intent Analyzer** classifies business intent and routes deterministic vs agentic work; "
            "**The Dispute Judge** handles contextual exceptions requiring evidence reasoning. Path C tasks stay in this "
            "layer and are executed with confidence scoring, policy checks, and human escalation hooks. Path B tasks are "
            "delivered as deterministic workflow components such as routing, formatting, and validation engines. Path A "
            "tasks are pushed back to standard ERP APIs and data checks. Regional variations are managed through policy "
            "injection and adapter patterns in the side-car, not through core transaction branching. This architecture "
            "lets McCain scale automation without coupling business variability to ERP internals."
        ),
    )

    _add_unique_section(
        section_order,
        section_registry,
        "## Technical Stack",
        (
            "System of Intelligence: LangGraph orchestration, policy guardrails, confidence routing, and optional LLM "
            "services configured through Azure/OpenAI-compatible settings. System of Record: SAP S/4HANA standard APIs, "
            "master data, and posting integrity controls. Integration contracts are protocol-labeled and observable: "
            "Webhook/AS2 intake, gRPC-style internal coordination, and OData/BAPI posting calls to ERP. Operational "
            "control points include schema checks, idempotency, payload validation, and exception queues. **Clean Core "
            "enforcement is explicit: all custom logic is isolated in the Side-Car layer and never embedded in the ERP "
            "kernel.** This separation protects upgradeability and reduces regression risk during SAP releases while "
            "still enabling high-adaptivity automation on top."
        ),
    )

    _add_unique_section(
        section_order,
        section_registry,
        "## Integration Design Deep Dive",
        (
            "The integration design follows a staged processing contract. Stage 1 handles omnichannel intake normalization "
            "to convert emails, EDI payloads, and partner messages into a canonical order event. Stage 2 performs "
            "classification and pathing: deterministic validations are executed through Path B services, while ambiguous "
            "or context-rich tasks are routed to Path C reasoning nodes. Stage 3 executes approved ERP interactions via "
            "standard API endpoints and performs post-transaction status callbacks to the side-car. Failure modes are "
            "handled in-band: malformed payloads trigger formatter retries, confidence failures trigger refinement loops, "
            "and prolonged uncertainty triggers human escalation. This design ensures that failure in one adapter or "
            "service does not corrupt core posting behavior."
        ),
    )

    _add_unique_section(
        section_order,
        section_registry,
        "## Agent Persona Reasoning Model",
        (
            "Agent personas are intentionally constrained by reasoning boundaries. The Intake Scribe is optimized for "
            "perception and structured extraction; it should not execute financial decisions. The Intent Analyzer is "
            "optimized for context classification and action routing; it determines whether a case is suitable for Path A, "
            "B, or C and records rationale for auditability. The Dispute Judge is optimized for evidence-based reasoning "
            "in exception scenarios and must return both decision and evidence chain. Together these personas create a "
            "transparent cognitive assembly line where each decision is attributable, reviewable, and reversible. This "
            "design lowers black-box risk and supports phased trust adoption."
        ),
    )

    _add_unique_section(
        section_order,
        section_registry,
        "## The Trust Gap Protocol",
        (
            f"Current operating mode defaults to **{trust_gap_phase}**. In Shadow, agents produce recommendations while "
            "humans keep execution authority and annotate decision quality gaps. In Co-Pilot, high-confidence low-risk "
            "steps can execute with explicit override and sampling audits. In Autopilot, approved lanes execute "
            "touchlessly with continuous telemetry, rollback hooks, and policy drift detection. The confidence threshold "
            "is strictly greater than 95%; anything at or below threshold is routed back to refinement. If loop limits are "
            "reached, the process hard-stops into human escalation rather than silently degrading quality."
        ),
    )

    _add_unique_section(
        section_order,
        section_registry,
        "## Path Design Decisions",
        "\n".join(decision_lines) if decision_lines else "- No decisions available.",
    )

    _add_unique_section(
        section_order,
        section_registry,
        "## Regional Policy Registry",
        (
            "The policy registry below captures normalized regional signals used to drive runtime behavior in the "
            "orchestration layer.\n\n"
            f"```json\n{regional_nuances}\n```"
        ),
    )

    _add_unique_section(
        section_order,
        section_registry,
        "## Delivery and Rollout Plan",
        (
            "Wave 1 establishes mandatory synthesis and confidence gating with human approval checkpoints. Wave 2 expands "
            "deterministic automations and adapter hardening for region-specific channels. Wave 3 scales approved agentic "
            "lanes with deeper telemetry, cost controls, and governance scorecards. KPI packs include touchless rate, "
            "manual touch reduction, exception turnaround, posting accuracy, and confidence distribution by task type. "
            "Exit criteria for each wave include audit evidence, rollback readiness, and trend stability over multiple "
            "business cycles."
        ),
    )

    _add_unique_section(
        section_order,
        section_registry,
        "## Appendix: Control and Operability Baseline",
        (
            "Core operability controls include schema validation, deterministic retries, idempotency keys, payload lineage, "
            "and cross-system correlation IDs. Governance controls include policy versioning, role-based approval, and "
            "exception triage SLAs. Reliability controls include dead-letter routing, retry budget limits, and monitored "
            "degradation paths. These controls make the automation stack production-safe while maintaining separation of "
            "concerns between side-car intelligence and ERP record integrity."
        ),
    )

    _add_unique_section(
        section_order,
        section_registry,
        "## Executive Simplified Summary",
        (
            "This design gives McCain one intelligent intake layer that reduces manual work and speeds order processing "
            "across regions. By keeping custom logic in the Side-Car and using only standard ERP APIs, the solution "
            "protects SAP stability and lowers upgrade risk. The trust-gated rollout lets the business scale automation "
            "safely while improving accuracy, cycle time, and service quality."
        ),
    )

    report = _render_report_from_sections(report_title, section_order, section_registry)
    expansion_block = (
        "Further technical detail: event payload contracts are versioned and backward-compatible, policy decisions are "
        "traceable to explicit evidence chains, side-car services are horizontally scalable, and rollout governance uses "
        "measurable confidence and exception KPIs to prevent quality drift."
    )
    while count_words(report) < settings.min_report_words:
        section_registry["## Delivery and Rollout Plan"] = (
            f"{section_registry['## Delivery and Rollout Plan']}\n\n{expansion_block}"
        )
        report = _render_report_from_sections(report_title, section_order, section_registry)

    return report


def _is_region_match(region: str, candidates: set[str]) -> bool:
    region_norm = region.strip().lower()
    return any(token in region_norm for token in candidates)


def _build_visual_architecture_xml(state: dict[str, Any]) -> str:
    context_region = str(state.get("context_region", "Global")).strip()
    is_south_africa = _is_region_match(context_region, {"south africa", "za", "sa"})
    is_uruguay = _is_region_match(context_region, {"uruguay"})
    is_china = _is_region_match(context_region, {"china"})

    lines: list[str] = []
    lines.append("graph TD")
    lines.append("  %% Zone A: External_Intake")
    lines.append('  subgraph External_Intake ["External Intake"]')
    lines.append("    CH_EMAIL([Email/PDF Intake]):::external")
    lines.append("    CH_CHAT([WhatsApp/Chat Intake]):::external")
    lines.append("    CH_EDI([EDI Intake]):::external")
    if is_south_africa:
        lines.append("    SA_VECTOR[(Vector 3PL)]:::persistence")
    if is_uruguay:
        lines.append("    UY_SYNC{{Power Street Sync}}:::agent")
    if is_china:
        lines.append("    CN_GATEWAY[Digital Hub Gateway]:::core")
    lines.append("  end")
    lines.append("")
    lines.append("  %% Zone B: Agentic_SideCar")
    lines.append('  subgraph Agentic_SideCar ["Agentic SideCar"]')
    lines.append("    AG_SCRIBE{{The Scribe}}:::agent")
    lines.append("    AG_INTENT{{Intent Analyzer}}:::agent")
    lines.append("    AG_DISPUTE{{Dispute Judge}}:::agent")
    lines.append("    WF_ROUTER([Email Router]):::workflow")
    lines.append("    WF_VALIDATOR([Data Validator]):::workflow")
    lines.append("    WF_FORMAT([Formatting Engine]):::workflow")
    lines.append("    DB_POLICY[(Regional Policy DB)]:::persistence")
    lines.append("  end")
    lines.append("")
    lines.append("  %% Zone C: Clean_Core_ERP")
    lines.append('  subgraph Clean_Core_ERP ["Clean Core ERP"]')
    lines.append("    ERP_VA01[VA01 API]:::core")
    lines.append("    ERP_MD[Master Data Check]:::core")
    lines.append("    ERP_POST[Final Order Posting]:::core")
    lines.append("    DB_S4[(S/4HANA Master Data)]:::persistence")
    lines.append("  end")
    lines.append("")
    lines.append("  %% Intake routing with regional logic")
    if is_china:
        lines.append("  CH_EMAIL -->|Webhook| CN_GATEWAY")
        lines.append("  CH_CHAT -->|Webhook| CN_GATEWAY")
        lines.append("  CH_EDI -->|AS2| CN_GATEWAY")
        if is_south_africa:
            lines.append("  SA_VECTOR -.->|Backward Integration API| CN_GATEWAY")
        lines.append("  CN_GATEWAY -->|gRPC| WF_ROUTER")
    elif is_uruguay:
        lines.append("  CH_EMAIL -->|Webhook| UY_SYNC")
        lines.append("  CH_CHAT -->|Webhook| UY_SYNC")
        lines.append("  CH_EDI -->|AS2| UY_SYNC")
        lines.append("  UY_SYNC -->|gRPC| AG_SCRIBE")
    else:
        lines.append("  CH_EMAIL -->|Webhook| WF_ROUTER")
        lines.append("  CH_CHAT -->|Webhook| WF_ROUTER")
        lines.append("  CH_EDI -->|AS2| WF_ROUTER")
    if is_south_africa and not is_china:
        lines.append("  SA_VECTOR -.->|Backward Integration API| WF_ROUTER")
    lines.append("")
    lines.append("  %% Side-Car orchestration flow")
    lines.append("  WF_ROUTER -.->|gRPC| AG_SCRIBE")
    lines.append("  AG_SCRIBE -->|JSON Payload| AG_INTENT")
    lines.append("  AG_INTENT -.->|Policy Query API| DB_POLICY")
    lines.append("  AG_INTENT -->|Validation RPC| WF_VALIDATOR")
    lines.append("  WF_VALIDATOR -->|Schema Rules| WF_FORMAT")
    lines.append("  AG_INTENT -->|Exception Context| AG_DISPUTE")
    lines.append("  AG_DISPUTE -.->|Case Resolution API| ERP_VA01")
    lines.append("")
    lines.append("  %% Clean Core standard processing")
    lines.append("  WF_FORMAT -.->|OData API| ERP_VA01")
    lines.append("  ERP_VA01 -->|BAPI/OData| ERP_MD")
    lines.append("  ERP_MD -.->|Master Data Read| DB_S4")
    lines.append("  ERP_MD ==>|OData API| ERP_POST")
    lines.append("  ERP_POST -->|Status Webhook| WF_ROUTER")
    lines.append("")
    lines.append("  %% Visual classes")
    lines.append("  classDef external fill:#E3F2FD,stroke:#1E88E5,color:#0D47A1,stroke-width:1px;")
    lines.append("  classDef agent fill:#FFF3CD,stroke:#B8860B,color:#5D4037,stroke-width:2px;")
    lines.append("  classDef workflow fill:#F5F5F5,stroke:#616161,color:#263238,stroke-width:1px;")
    lines.append("  classDef core fill:#ECEFF1,stroke:#455A64,color:#263238,stroke-width:1.5px;")
    lines.append("  classDef persistence fill:#E8F5E9,stroke:#2E7D32,color:#1B5E20,stroke-width:1.5px;")

    mermaid_data = "\n".join(lines)
    return f"""<VisualArchitecture version="2.0">
  <Region>{escape(context_region)}</Region>
  <DiagramType>Tiered_Agentic_SideCar</DiagramType>
  <MermaidData><![CDATA[
{mermaid_data}
  ]]></MermaidData>
</VisualArchitecture>"""


def Blueprint_Node(state: dict[str, Any], settings: Settings) -> dict[str, Any]:
    if not state.get("manual_approval", False):
        raise ValueError(
            "Trust Gap Protocol requires manual approval before Blueprint_Node execution. "
            "Set manual_approval=true only after human checkpoint review."
        )

    strategy_report = _build_strategy_report(state, settings)
    mermaid_xml = _build_visual_architecture_xml(state)

    validate_strategy_report(strategy_report, min_words=settings.min_report_words)
    validate_mermaid_xml(mermaid_xml)

    phase_status = dict(state.get("phase_status", {}))
    phase_status["phase_3_blueprint_generation"] = "completed"

    return {
        "strategy_report_markdown": strategy_report,
        "mermaid_xml": mermaid_xml,
        "refined_blueprint": {
            "strategy_report_markdown": strategy_report,
            "mermaid_xml": mermaid_xml,
        },
        "phase_status": phase_status,
    }
